<a href="https://colab.research.google.com/github/Carolduplex/bootcampo_FDAMANHA/blob/main/Gastos_Faturamento_(Capivara).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importante base de gastos
import pandas as pd
import numpy as np
dfg = pd.read_csv('/content/gastos.xlsx - Sheet 1.csv')
dff = pd.read_csv('/content/Faturamento.xlsx - Sheet 1.csv')

In [ ]:
#Reconhecimento da Base
dfg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4517 entries, 0 to 4516
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Data Faturamento  4517 non-null   object
 1   Valor             4517 non-null   object
 2   Tipo_gasto        4517 non-null   object
 3   Pagamento         4517 non-null   object
 4   Empresa           4517 non-null   object
dtypes: object(5)
memory usage: 176.6+ KB

In [ ]:
dfg['Valor'].dtype

dtype('O')

In [ ]:
dfg['Valor'] = dfg['Valor'].str.replace(',','.') #devido aos números que tinham vírgulas não era possível converter para float.Por isso essa linha para conseguir converter

In [ ]:
#Convertendo Data e valor.
dfg['Data Faturamento'] = pd.to_datetime(dfg['Data Faturamento'])
dfg['Valor'] = pd.to_numeric(dfg['Valor'])
dfg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4517 entries, 0 to 4516
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Data Faturamento  4517 non-null   datetime64[ns]
 1   Valor             4517 non-null   float64
 2   Tipo_gasto        4517 non-null   object
 3   Pagamento         4517 non-null   object
 4   Empresa           4517 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 176.6+ KB

In [ ]:
new_var0 = dfg['Data Faturamento'].dtype
new_var0
dfg['Valor'].dtype

dtype('float64')

In [ ]:
#última verificação de valores nulos
dfg.isna().sum()

Data Faturamento    0
Valor               0
Tipo_gasto          0
Pagamento           0
Empresa             0
dtype: int64

In [ ]:
#Procurar Valores 0
zero_in_dfg = (dfg == 0).any().any()
print("Há algum zero no DataFrame inteiro?")
print(zero_in_dfg)

Há algum zero no DataFrame inteiro?
False

In [ ]:
#dados tabela Faturamento
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mes_Ano      44 non-null     object
 1   Faturamento  44 non-null     object
dtypes: object(2)
memory usage: 832.0+ bytes

In [ ]:
dff['Faturamento'] = dff['Faturamento'].str.replace(',', '.')

In [ ]:
dff['Mes_Ano'] = pd.to_datetime(dff['Mes_Ano'])
dff['Faturamento'] = pd.to_numeric(dff['Faturamento'])
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mes_Ano      44 non-null     datetime64[ns]
 1   Faturamento  44 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 832.0 bytes

In [ ]:
#verificação de valores nulos
dff.isna().sum()

Mes_Ano        0
Faturamento    0
dtype: int64

In [ ]:
#Procurar Valores 0
zero_in_dff = (dff == 0).any().any()
print("Há algum zero no DataFrame inteiro?")
print(zero_in_dff)

Há algum zero no DataFrame inteiro?
False

In [ ]:
# Concatenar os dataframes verticalmente
df_concat = pd.concat([dfg, dff], ignore_index=True)

In [ ]:
print(dfg.head())
print(dff.head())

  Data Faturamento   Valor                Tipo_gasto Pagamento    Empresa
0       2020-02-01   100.0  Contratação Divulgadores        3x  Empresa 2
1       2020-02-03  1074.0  Contratação Divulgadores        1x  Empresa 1
2       2020-02-07   110.0  Contratação Divulgadores        2x  Empresa 1
3       2020-02-08   140.0  Contratação Divulgadores        1x  Empresa 1
4       2020-02-16   361.0  Contratação Divulgadores        3x  Empresa 2
     Mes_Ano  Faturamento
0 2020-02-01  454999.9059
1 2020-03-01  349186.2904
2 2020-04-01  362987.4443
3 2020-05-01  374496.6349
4 2020-06-01  385705.8323

In [ ]:
print('id' in dfg.columns)
print('id' in dff.columns)

False
False

In [ ]:
common_cols = set(dfg.columns).intersection(dff.columns)
print(common_cols)

set()

In [ ]:
print(f"common_cols: {type(common_cols)}")

common_cols: <class 'set'>

In [ ]:
if isinstance(common_cols, set):
    common_cols = list(common_cols)
    print(f"common_cols after conversion: {common_cols}")

common_cols after conversion: []

In [ ]:
dfg['Tipo_gasto'].unique()

array(['Contratação Divulgadores', 'Campanha Facebook',
       'Campanha facebook', 'Campanha Facebok', 'Campanha Facebook ',
       'Contratação GoogleAds', 'Contratação GoogleAdds',
       'Contratação  GoogleAds', 'Contratação GoogleAds ',
       'Campanha Instagran', 'Campanha Instagram', 'Campanha instagram',
       'Contratação Propagandas Outdoor',
       'Contratação Propagandas Outdor ',
       'Contratação Propagandas Outdoor ',
       'Contratação Propaganda Rádio ', 'Contratação Propaganda Radio',
       'Contratação Propaganda Rádio', 'Contratação Propaganda Radio ',
       'Contratacão Propaganda Revistas',
       'Contratação Propaganda Revistas',
       'Contratação Propaganda Revista',
       'Contratação Propaganda Revistas ', 'Campanha Tiktok',
       'Campanha Tik-tok', 'Campanha Tik tok', 'Campanha tiktok',
       'Contratação Propaganda tv', 'Contratação Propaganda TV',
       'Contratação Propaganda televisão', 'Campanha Youtube'],
      dtype=object)

In [ ]:

new_var = dfg.replace('Campanha Facebok', 'Campanha Facebook').replace('Campanha Facebook ', 'Campanha Facebook')

dfg = new_var

dfg = dfg.replace('Contratação GoogleAds', 'Contratação GoogleAds').replace('Contratação GoogleAdds',
         'Contratação GoogleAds').replace('Contratação  GoogleAds', 'Contratação GoogleAds').replace('Contratação GoogleAds ', 'Contratação GoogleAds')

dfg = dfg.replace('Campanha Instagran', 'Campanha Instagram').replace('Campanha Instagram', 'Campanha Instagram').replace('Campanha instagram',
 'Camapanha Instagram').replace('Campanha Instagram','Camapanha Instagram')

dfg = dfg.replace('Contratação Propagandas Outdoor', 'Campanha Outdoor').replace('Contratação Propagandas Outdor ',
         'Campanha Outdoor').replace('Contratação Propagandas Outdoor ', 'Campanha Outdoor')

dfg = dfg.replace('Contratação Propaganda Rádio ', 'Contratação Propaganda Rádio').replace('Contratação Propaganda Radio',
         'Contratação Propaganda Rádio').replace('Contratação Propaganda Rádio', 'Contratação Propaganda Rádio').replace('Contratação Propaganda Radio ', 'Contratação Propaganda Rádio')

dfg = dfg.replace('Contratacão Propaganda Revistas', 'Contratacão Propaganda Revistas').replace('Contratação Propaganda Revistas',
         'Contratacão Propaganda Revistas').replace('Contratação Propaganda Revista', 'Contratacão Propaganda Revistas').replace('Contratação Propaganda Revistas ', 'Contratacão Propaganda Revistas')

dfg = dfg.replace('Campanha Tiktok', 'Campanha Tiktok').replace('Campanha Tik-tok', 'Campanha Tiktok').replace('Campanha Tik tok', 'Campanha Tiktok').replace('Campanha tiktok', 'Campanha Tiktok')

dfg = dfg.replace('Contratação Propaganda tv', 'Contratação Propaganda TV').replace('Contratação Propaganda televisão', 'Contratação Propaganda TV')

In [ ]:
dfg['Tipo_gasto'].unique()

array(['Contratação Divulgadores', 'Campanha Facebook',
       'Campanha facebook', 'Contratação GoogleAds',
       'Camapanha Instagram', 'Campanha Outdoor',
       'Contratação Propaganda Rádio', 'Contratacão Propaganda Revistas',
       'Campanha Tiktok', 'Contratação Propaganda TV', 'Campanha Youtube'],
      dtype=object)

In [ ]:
dfg.groupby('Tipo_gasto').sum(numeric_only=True)

                                         Valor
Tipo_gasto
Camapanha Instagram              137960.317212
Campanha Facebook                112521.865598
Campanha Outdoor                 137314.996839
Campanha Tiktok                  135526.315190
Campanha Youtube                 130431.017909
Campanha facebook                 19663.152236
Contratacão Propaganda Revistas  129975.642961
Contratação Divulgadores         138104.642011
Contratação GoogleAds            126549.131538
Contratação Propaganda Rádio     136637.819290
Contratação Propaganda TV        118641.297677

In [ ]:
#Valor gastos pelas empresas
dfg.groupby('Empresa')[['Valor']].sum(numeric_only=True)

                    Valor
Empresa
Empresa 1    96268.961447
Empresa 10   43468.768924
Empresa 2    41835.680564
Empresa 3   365168.987962
Empresa 4   170933.680182
Empresa 5   257924.894240
Empresa 6   127329.865688
Empresa 7    81617.385082
Empresa 8    44931.746456
Empresa 9    93846.227915

In [ ]:
print(dff.head())
print(dfg.head())

     Mes_Ano  Faturamento
0 2020-02-01  454999.9059
1 2020-03-01  349186.2904
2 2020-04-01  362987.4443
3 2020-05-01  374496.6349
4 2020-06-01  385705.8323
  Data Faturamento   Valor                Tipo_gasto Pagamento    Empresa
0       2020-02-01   100.0  Contratação Divulgadores        3x  Empresa 2
1       2020-02-03  1074.0  Contratação Divulgadores        1x  Empresa 1
2       2020-02-07   110.0  Contratação Divulgadores        2x  Empresa 1
3       2020-02-08   140.0  Contratação Divulgadores        1x  Empresa 1
4       2020-02-16   361.0  Contratação Divulgadores        3x  Empresa 2

In [ ]:
print(dfg.dtypes)
print(dff.dtypes)

Data Faturamento    datetime64[ns]
Valor                      float64
Tipo_gasto                  object
Pagamento                   object
Empresa                     object
dtype: object
Mes_Ano        datetime64[ns]
Faturamento           float64
dtype: object

In [ ]:
dfg.groupby('Tipo_gasto')['Valor'].sum(numeric_only=True)

Tipo_gasto
Camapanha Instagram                137960.317212
Campanha Facebook                  112521.865598
Campanha Outdoor                   137314.996839
Campanha Tiktok                    135526.315190
Campanha Youtube                   130431.017909
Campanha facebook                   19663.152236
Contratacão Propaganda Revistas    129975.642961
Contratação Divulgadores           138104.642011
Contratação GoogleAds              126549.131538
Contratação Propaganda Rádio       136637.819290
Contratação Propaganda TV          118641.297677
Name: Valor, dtype: float64

In [ ]:
dfg.groupby('Empresa')[['Valor']].sum(numeric_only=True)
data_gastos = pd.DatetimeIndex(dfg['Data Faturamento'])

dfg['Mes_Ano'] = data_gastos.strftime("%m/%Y")
dfg['Ano'] = data_gastos.year
dfg.groupby('Mes_Ano')[['Valor']].sum(numeric_only=True) #Calculando o TOTAL de gastos MENSAL

                Valor
Mes_Ano
01/2021  27802.037487
01/2022  29647.776563
01/2023  31289.154568
02/2020  33944.285322
02/2021  28602.263149
02/2022  31661.342210
02/2023  24126.825064
03/2020  26991.507723
03/2021  25451.684267
03/2022  30277.169337
03/2023  30943.705821
04/2020  30865.555619
04/2021  28302.658988
04/2022  34224.110053
04/2023  35745.431706
05/2020  27328.352954
05/2021  33396.862213
05/2022  27150.266589
05/2023  26959.623718
06/2020  30137.095531
06/2021  33008.710813
06/2022  30206.098800
06/2023  35496.571002
07/2020  27404.572014
07/2021  31552.866793
07/2022  32564.427618
07/2023  27985.314374
08/2020  30009.484585
08/2021  26727.175473
08/2022  34831.339888
08/2023  30879.994800
09/2020  30590.811114
09/2021  29853.642639
09/2022  30341.135435
09/2023  24996.541149
10/2020  27096.406108
10/2021  31506.561935
10/2022  31228.548302
11/2020  29847.624231
11/2021  27642.101828
11/2022  33090.069746
12/2020  29577.024130
12/2021  28718.981829
12/2022  33322.484975

In [ ]:
#Calculando a MÉDIA de gastos de MENSAL

dfg.groupby('Mes_Ano')[['Valor']].mean(numeric_only=True)

              Valor
Mes_Ano
01/2021  289.604557
01/2022  262.369704
01/2023  297.991948
02/2020  353.586305
02/2021  297.940241
02/2022  282.690555
02/2023  271.087922
03/2020  313.854741
03/2021  276.648742
03/2022  291.126628
03/2023  294.701960
04/2020  308.655556
04/2021  288.802643
04/2022  305.572411
04/2023  330.976219
05/2020  303.648366
05/2021  303.607838
05/2022  271.502666
05/2023  280.829414
06/2020  292.593160
06/2021  297.375773
06/2022  267.310609
06/2023  328.671954
07/2020  276.813859
07/2021  300.503493
07/2022  288.180775
07/2023  291.513691
08/2020  277.865598
08/2021  275.537891
08/2022  300.270171
08/2023  302.745047
09/2020  315.369187
09/2021  301.551946
09/2022  297.462112
09/2023  268.780012
10/2020  263.071904
10/2021  302.947711
10/2022  291.855592
11/2020  278.949759
11/2021  271.000998
11/2022  295.447051
12/2020  292.841823
12/2021  263.476898
12/2022  326.691029

In [ ]:
#Calculando o TOTAL de gastos ANUAL

dfg_anual=dfg.groupby('Ano')[['Valor']].sum(numeric_only=True)

In [ ]:
#Extraindo e criando coluna de ANO do Faturamento

data_fat = pd.DatetimeIndex(dff['Mes_Ano'])

dff['Ano'] = data_fat.year

In [ ]:
#Faturamento MENSAL

dff.groupby('Mes_Ano')[['Faturamento']].sum(numeric_only=True)

            Faturamento
Mes_Ano
2020-02-01  454999.9059
2020-03-01  349186.2904
2020-04-01  362987.4443
2020-05-01  374496.6349
2020-06-01  385705.8323
2020-07-01  336273.1283
2020-08-01  389036.0341
2020-09-01  368193.3450
2020-10-01  412218.5352
2020-11-01  367090.3283
2020-12-01  355580.5332
2021-01-01  413642.4929
2021-02-01  400055.4975
2021-03-01  416830.6334
2021-04-01  362469.7280
2021-05-01  376283.3675
2021-06-01  421333.1125
2021-07-01  421268.6996
2021-08-01  417417.0739
2021-09-01  418007.1696
2021-10-01  383353.8098
2021-11-01  352580.9966
2021-12-01  378762.3148
2022-01-01  432216.0098
2022-02-01  378677.9814
2022-03-01  384351.4137
2022-04-01  434649.0928
2022-05-01  451570.2820
2022-06-01  411315.8131
2022-07-01  424556.7258
2022-08-01  380087.2815
2022-09-01  350925.9576
2022-10-01  395913.1824
2022-11-01  446261.6769
2022-12-01  421677.4497
2023-01-01  404743.4670
2023-02-01  451517.7543
2023-03-01  379384.7368
2023-04-01  439842.2154
2023-05-01  389718.6425
2023-06-01  394072.5530
2023-07-01  448831.3566
2023-08-01  433155.0657
2023-09-01  387471.1925

In [ ]:
#Faturamento ANUAL

dff.groupby('Ano')[['Faturamento']].sum(numeric_only=True)

       Faturamento
Ano
2020  4.155768e+06
2021  4.762005e+06
2022  4.912203e+06
2023  3.728737e+06

In [ ]:
dff_total=dff['Faturamento'].sum()

In [ ]:
dfg_total = dfg['Valor'].sum()

In [ ]:
roi = ((dff['Faturamento'].sum() - dfg['Valor'].sum()) / dfg['Valor'].sum()) * 100

print(f"ROI: {roi:.2f}%")

ROI: 1226.86%

In [ ]:
roi = ((dff['Faturamento'].sum() - dfg['Valor'].sum()) / dfg['Valor'].sum()) * 100
roi_arredondado = round(roi, 2)

print(f"ROI: {roi_arredondado:.1f}%")

ROI: 1226.9%